os: Visual Studio 2015

platform:
  - x86
  - x64

configuration:
  - stable
  - master

clone_script:
  - git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - git checkout -qf %APPVEYOR_REPO_COMMIT%
  - git submodule update --init yori-%CONFIGURATION%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\yori-%CONFIGURATION%
  - git tag v2.5 ca6f216
  - for /f %%v IN ('git describe --tags') do set VERSION=%%v
  - call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%
  - nmake
  - 7z a ../yori-%CONFIGURATION%-%VERSION%-%PLATFORM%.7z bin

artifacts:
  - path: yori-*.7z
